spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mob_tally
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true