spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration
  profiles:
    active: dev # available options are dev, stage and prod
  application:
    name: Tally
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true