spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tally
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    continue-on-error: false
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

flyway:
  locations: classpath:/db/migration